version: '3.1'

services:
  frontendserver:
    build: ./frontendserver/
    container_name: frontendserver
    image: frontendserver
    ports:
      - 8080:8080
    depends_on:
      - appserver

  appserver:
    build: ./appserver/
    container_name: appserver
    image: appserver
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - mongo
      - postgres

  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    volumes:
      - "./mongodb/:/data/db/"

  mongo-express:
    image: mongo-express:0.49
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopw
    depends_on:
      - mongo

  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    volumes:
      - "./postgres/:/var/lib/postgresql/data/"

  adminer:
    image: adminer:4.7
    restart: always
    ports:
      - 8083:8080
    depends_on:
      - postgres

