version: '3.1'

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    volumes:
      - "./postgres/:/var/lib/postgresql/data/"

  adminer:
    image: adminer:4.7
    restart: always
    ports:
      - 8083:8080
    depends_on:
      - postgres

