name: Firebase deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: npm install 
      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: wirvsvirus-19373
